tinyMCE.addI18n( "de.photonav", {
		image_url: "Bild URL",
		mode: "Modus",
			mode_move: "Scrollen",
			mode_drag: "Draggen",
			mode_360: "360° Draggen",
		popup: "Popup",
			pop_none: "Keines",
			pop_colorbox: "Colorbox",
		animation: "Animation",
			ani_none: "Keine",
			ani_left: "Links",
			ani_right: "Rechts",
			ani_zoom: "Zoomen",
		position: "Startposition",
			pos_center: "Zentriert",
			pos_left: "Links",
			pos_right: "Rechts",
		label: "Beschriftung",
		width: "Rahmenbreite",
		height: "Rahmenhöhe",
} );