tinyMCE.addI18n( "en.photonav", {
		image_url: "Image URL",
		mode: "Mode",
			mode_move: "Move",
			mode_drag: "Drag",
			mode_360: "Drag 360",
		popup: "Popup style",
			pop_none: "None",
			pop_colorbox: "Colorbox",
		animation: "Animation",
			ani_none: "None",
			ani_left: "Left",
			ani_right: "Right",
			ani_zoom: "Zoom",
		position: "Initial position",
			pos_center: "Centered",
			pos_left: "Left",
			pos_right: "Right",
		label: "Show label",
		width: "Frame width",
		height: "Frame height",
} );